# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56af140640342729a202f6d26162a01529147c375b38e9a5db069559c5103349272b5e7b3c18bd00fa61c8eb59a47663a79d9f3e59ed2570bee04106c0d3172f

test:
  secret_key_base: 57ab6ca95806fb1f9a7d68f7fd3410544991d96088b41056e0cc417a122a80df212fc37db630884de8d1ad8f7a8bbd803cba378763d3fb298b532f95b7e819a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
